-- Condtraints

ALTER TABLE ExtraLesson
ADD CONSTRAINT FK_EL_CLASS FOREIGN KEY(CID) REFERENCES Class(CID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Teaching
ADD CONSTRAINT FK_T_USER FOREIGN KEY(UserID) REFERENCES Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Teaching
ADD CONSTRAINT FK_T_CLASS FOREIGN KEY(CID) REFERENCES Class(CID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE BelongsTo
ADD CONSTRAINT FK_BT_USER FOREIGN KEY(UserID) REFERENCES Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE BelongsTo
ADD CONSTRAINT FK_BT_CLASS FOREIGN KEY(CID) REFERENCES Class(CID) ON DELETE CASCADE ON UPDATE CASCADE;